include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - avoid_print
    - prefer_final_fields
    - always_use_package_imports

analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    
