workflows:
  android-release:
    name: Awaaz Room V13 Release APK
    max_build_duration: 45
    instance_type: mac_mini_m2

    environment:
      flutter: 3.47.2

    scripts:
      - name: Get packages
        script: |
          flutter clean
          flutter pub get

      - name: Build Android APK (Release)
        script: |
          flutter build apk --release -t lib/main.dart

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
