workflows:
  android-release:
    name: Build Android Release
    environment:
      flutter: stable

    scripts:
      - name: Move to project root
        script: |
          cd awaaz_room_v13

      - name: Get packages
        script: |
          flutter pub get

      - name: Build APK (Release)
        script: |
          flutter build apk --release -t lib/main.dart

    artifacts:
      - awaaz_room_v13/build/app/outputs/flutter-apk/app-release.apk
