name: Generate Android Folder

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Flutter SDK manually
        run: |
          git clone https://github.com/flutter/flutter.git --branch stable --depth 1 _flutter
          echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH
          
      - name: Create Android Platform
        run: flutter create --platforms=android --no-pub.
        
      - name: Commit and Push Android Folder
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add android/
          git commit -m "Auto-generate android folder" || echo "No changes to commit"
          git push
          
