name: Generate Android Folder

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
          
      - name: Create Android Platform
        run: flutter create --platforms=android .
        
      - name: Commit and Push Android Folder
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add android/
          git commit -m "Auto-generate android folder" || echo "No changes to commit"
          git push
          
